services:
  remnawave-status-dashboard:
    image: aliquamsiderea/remnawave-status-dashboard:0.1.0
    container_name: 'remnawave-status-dashboard'
    hostname: remnawave-status-dashboard
    #uncomment if you want build
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - '3001:3001'
    networks:
      - remnawave-network
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_BASE_URL=${API_BASE_URL}
      - API_TOKEN=${API_TOKEN}
    env_file:
      - .env.production
#    volumes:
#      - ./public/theme.ts:/src/app/theme/theme.ts # кастомные стили
#      - ./public/Logo.png:/app/public/Logo.png # Кастомное лого
    restart: unless-stopped

networks:
  remnawave-network:
    external: true
